// Test utility to verify reset link functionality
export const testResetLinkGeneration = () => {
  console.log('=== Testing Reset Link Flow ===')
  
  // Simulate the URL that would be generated by the backend
  const testEmail = 'test@example.com'
  const testTimestamp = Date.now()
  const testExpires = testTimestamp + 3600 // 1 hour from now
  
  // This simulates the URL structure from Symfony's signed URLs
  const testUrl = `http://localhost:8000/auth/verify-forgot_password?email=${encodeURIComponent(testEmail)}&timestamp=${testTimestamp}&expires=${testExpires}&signature=abc123`
  
  console.log('Test URL:', testUrl)
  
  // Test URL parsing
  const urlParams = new URLSearchParams(testUrl.split('?')[1])
  const email = urlParams.get('email')
  const timestamp = urlParams.get('timestamp')
  const expires = urlParams.get('expires')
  
  console.log('Parsed parameters:')
  console.log('- Email:', email)
  console.log('- Timestamp:', timestamp)
  console.log('- Expires:', expires)
  
  // Test expiration logic
  const now = Date.now()
  const isExpired = now > parseInt(expires || '0')
  
  console.log('Expiration check:')
  console.log('- Current time:', now)
  console.log('- Expires at:', expires)
  console.log('- Is expired:', isExpired)
  
  return {
    url: testUrl,
    email,
    timestamp,
    expires,
    isExpired
  }
}

export const simulateEmailClick = (resetUrl: string) => {
  console.log('\n=== Simulating Email Link Click ===')
  console.log('User clicks on:', resetUrl)
  
  // This simulates what happens when the user clicks the email link
  window.location.href = resetUrl
  
  return resetUrl
}
